//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lesson08.ptth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUA
    {
        public string PtthMaSV { get; set; }
        public string PtthMaMH { get; set; }
        public Nullable<decimal> PtthDiem { get; set; }
    
        public virtual MONHOC MONHOC { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
