//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lesson08.ptth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SINHVIEN()
        {
            this.KETQUAs = new HashSet<KETQUA>();
        }
    
        public string PtthMaSV { get; set; }
        public string PtthHoSV { get; set; }
        public string PtthTenSV { get; set; }
        public Nullable<bool> PtthPhai { get; set; }
        public Nullable<System.DateTime> PtthNgaySinh { get; set; }
        public string PtthNoiSinh { get; set; }
        public string PtthMaKH { get; set; }
        public Nullable<decimal> PtthHocBong { get; set; }
        public Nullable<decimal> PtthDiemTrungBinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KETQUA> KETQUAs { get; set; }
    }
}
