//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtthK22CNT4Lesson11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtthCategory
    {
        public int PtthID { get; set; }
        public string PtthCateName { get; set; }
        public Nullable<bool> PtthStatus { get; set; }
    }
}
