//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtthK22CNT4Lesson11.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PtthK22CNT4Lesson11DbEntities : DbContext
    {
        public PtthK22CNT4Lesson11DbEntities()
            : base("name=PtthK22CNT4Lesson11DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PtthCategory> PtthCategories { get; set; }
        public virtual DbSet<PtthProduct> PtthProducts { get; set; }
    }
}
