//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtthLesson12.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhamThiThuHuyen_2210900030Entities : DbContext
    {
        public PhamThiThuHuyen_2210900030Entities()
            : base("name=PhamThiThuHuyen_2210900030Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ptth_MaSach> Ptth_MaSach { get; set; }
        public virtual DbSet<Ptth_MaTG> Ptth_MaTG { get; set; }
    }
}
