//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtthLesson12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ptth_MaTG
    {
        public string Ptth_MaTG1 { get; set; }
        public string Ptth_TenTG { get; set; }
    }
}
