//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtthLesson12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ptth_MaSach
    {
        public string Ptth_MaSach1 { get; set; }
        public string Ptth_TenSach { get; set; }
        public Nullable<int> Ptth_Sotrang { get; set; }
        public Nullable<int> Ptth_NamXB { get; set; }
        public string Ptth_MaTG { get; set; }
        public Nullable<bool> Ptth_TrangThai { get; set; }
    }
}
