//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtthK22CNT4Lesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtthAccount
    {
        public int PtthID { get; set; }
        public string PtthUserName { get; set; }
        public string PtthPassword { get; set; }
        public string PtthFullName { get; set; }
        public string PtthEmail { get; set; }
        public string PtthPhone { get; set; }
        public Nullable<bool> PtthActive { get; set; }
    }
}
