//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtthLesson07.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtthSinhVien
    {
        public string PtthMaSV { get; set; }
        public string PtthHoSV { get; set; }
        public string PtthTenSV { get; set; }
        public Nullable<bool> PtthPhai { get; set; }
        public string PtthEmail { get; set; }
        public string PtthPhone { get; set; }
        public string PtthMaKH { get; set; }
        public Nullable<bool> PtthTrangthai { get; set; }
    
        public virtual PtthKhoa PtthKhoa { get; set; }
    }
}
