//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtthLesson07.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtthKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PtthKhoa()
        {
            this.PtthSinhViens = new HashSet<PtthSinhVien>();
        }
    
        public string PtthMaKH { get; set; }
        public string PtthTenKh { get; set; }
        public Nullable<bool> PtthTrangthai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PtthSinhVien> PtthSinhViens { get; set; }
    }
}
